basePath: /api/
host: 127.0.0.1:8082
info:
  contact: {}
  description: API documentation for the Purchasing System
  title: Purchasing System API
  version: "1.0"
paths: {}
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-API-Key
    type: apiKey
swagger: "2.0"
