definitions:
  main.ApiResponse:
    properties:
      message:
        type: string
    type: object
  main.Image:
    properties:
      url_standard:
        type: string
      url_thumbnail:
        type: string
      url_tiny:
        type: string
    type: object
  main.Manufacturer:
    properties:
      name:
        type: string
    type: object
  main.Product:
    properties:
      currency:
        type: string
      description:
        type: string
      image:
        $ref: '#/definitions/main.Image'
      inventoryQty:
        type: integer
      manufacturer:
        type: string
      manufacturerPart:
        type: string
      modified:
        type: string
      orderQty:
        type: integer
      processRequest:
        type: string
      reorder:
        type: boolean
      season:
        type: string
      sku:
        type: string
      sortingRequest:
        type: string
      unit:
        type: string
      unitPrice:
        type: number
    type: object
info:
  contact: {}
paths:
  /api/productdelete:
    post:
      consumes:
      - application/json
      description: Deletes a product from the database based on its SKU
      parameters:
      - description: SKU of the product to delete
        in: body
        name: sku
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses: {}
      summary: Delete a product
      tags:
      - products
  /api/productinsert:
    post:
      consumes:
      - application/json
      description: Adds a new product to the database
      parameters:
      - description: Product to add
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/main.Product'
      produces:
      - application/json
      responses: {}
      summary: Insert new product
      tags:
      - products
  /api/products:
    get:
      consumes:
      - application/json
      description: Retrieves a list of products, with optional filtering parameters
      parameters:
      - description: Filter by internal SKU
        in: query
        name: sku_internal
        type: string
      - description: Filter by manufacturer code
        in: query
        name: manufacturer_code
        type: string
      - description: Filter by manufacturer SKU
        in: query
        name: sku_manufacturer
        type: string
      - description: Filter by processing request
        in: query
        name: processing_request
        type: string
      - description: Filter by sorting request
        in: query
        name: sorting_request
        type: string
      - description: Filter by unit
        in: query
        name: unit
        type: string
      - description: Filter by unit price
        in: query
        name: unit_price
        type: string
      - description: Filter by currency
        in: query
        name: Currency
        type: string
      - description: Filter by order quantity
        in: query
        name: order_qty
        type: string
      - description: Filter by reorder status
        in: query
        name: reorder
        type: string
      - description: Filter by season
        in: query
        name: season
        type: string
      - description: Limit number of results
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of products
          schema:
            items:
              $ref: '#/definitions/main.Product'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: List products
      tags:
      - products
  /api/productupdate:
    post:
      consumes:
      - application/json
      description: Updates a product in the database with the given SKU
      parameters:
      - description: Product information to be updated
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/main.Product'
      produces:
      - application/json
      responses:
        "200":
          description: Product successfully updated
          schema:
            $ref: '#/definitions/main.ApiResponse'
        "400":
          description: 'Bad Request: SKU is required'
          schema:
            $ref: '#/definitions/main.ApiResponse'
        "404":
          description: Product not found
          schema:
            $ref: '#/definitions/main.ApiResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.ApiResponse'
      summary: Update an existing product
      tags:
      - products
  /manufacturers:
    get:
      consumes:
      - application/json
      description: Retrieves a list of manufacturers from the database
      produces:
      - application/json
      responses:
        "200":
          description: List of manufacturers
          schema:
            items:
              $ref: '#/definitions/main.Manufacturer'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: List manufacturers
      tags:
      - manufacturers
swagger: "2.0"
